name: Bazel

on:
  pull_request: {}
  push: {}

jobs:
  build_and_test_ubuntu22:
    name: Linux Ubuntu 22.04 build <GCC 11.2.0>
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-gcc11

      - name: Build
        run: |
          cd test
          bazelisk build --config=gcc11 //...
